export const RESET_RESTAURANT_LIST = 'RESET_RESTAURANT_LIST';

//Restaurant types
export const RESTAURANT_LIST_START = 'RESTAURANT_LIST_START';
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS';
export const RESTAURANT_LIST_FAILURE = 'RESTAURANT_LIST_FAILURE';


//Entity types
export const ENTITY_DETAILS_START = 'ENTITY_DETAILS_START';
export const ENTITY_DETAILS_SUCCESS = 'ENTITY_DETAILS_SUCCESS';
export const ENTITY_DETAILS_FAILURE = 'ENTITY_DETAILS_FAILURE';

